# Generated by Django 2.1.2 on 2018-11-23 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombreciudad', models.CharField(max_length=50, unique=True, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombreestado', models.CharField(max_length=50, unique=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('genero', models.CharField(max_length=1, verbose_name='Género')),
                ('fechaIngreso', models.DateField(blank=True)),
                ('fechaNacimiento', models.DateField(null=True, verbose_name='Fecha de Nacimiento')),
                ('imagen', models.ImageField(upload_to='media/', verbose_name='Imagen')),
                ('Nombreestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Estado', verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo')),
                ('run', models.CharField(max_length=10, verbose_name='Run')),
                ('nombreCompleto', models.CharField(max_length=50, verbose_name='Nombre Completo')),
                ('fechaNaci', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('Nombreciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ciudad', verbose_name='Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=50, unique=True, verbose_name='Raza')),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombreregion', models.CharField(max_length=50, unique=True, verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='tipoVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipovivienda', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Vivienda')),
            ],
            options={
                'verbose_name': 'Tipo de Vivienda',
                'verbose_name_plural': 'Tipo de Viviendas',
            },
        ),
        migrations.AddField(
            model_name='postulante',
            name='Nombreregion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='tipovivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoVivienda', verbose_name='Tipo de Vivienda'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Raza', verbose_name='Raza'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region'),
        ),
    ]
